[package]
name = "aoc-2025-11-2"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aoc-2025-11-2"
path = "src/main.rs"

[dependencies]
ahash = { workspace = true }
pathfinding = { workspace = true }
