[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
foldhash = "0.2.0"
nohash = "0.2.0"
tinyset = "0.5.2"

[profile.release]
opt-level = 3
lto = true 
