[workspace]
resolver = "2"
members = ["solutions/*/*/*", "cli"]

[workspace.dependencies]
ahash = "0.8.12"
pathfinding = "4.14.0"
petgraph = { version = "0.8.3", features = ["rayon"] }
z3 = "0.19.5"

[profile.release]
opt-level = 3
lto = true
